version: '3.7'

services:
  redis_test:
    container_name: redis_test
    image: bitnami/redis:latest
    restart: always
    env_file: .env.test
    environment:
      - ALLOW_EMPTY_PASSWORD=no
networks:
  metascape:
    name: metascape
